# Generated by Django 4.2.2 on 2023-06-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
